# Generated by Django 2.0.6 on 2018-06-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('page_views', models.IntegerField(default=0)),
            ],
        ),
    ]
